/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.jdbc;

import com.mysecretwish.dao.*;
import com.mysecretwish.factory.*;
import com.mysecretwish.dto.*;
import com.mysecretwish.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class PreventiviServiziDaoImpl extends AbstractDAO implements PreventiviServiziDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT preventivi_servizi_id, descrizione_servizio, preventivi_id FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( preventivi_servizi_id, descrizione_servizio, preventivi_id ) VALUES ( ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET preventivi_servizi_id = ?, descrizione_servizio = ?, preventivi_id = ? WHERE preventivi_servizi_id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE preventivi_servizi_id = ?";

	/** 
	 * Index of column preventivi_servizi_id
	 */
	protected static final int COLUMN_PREVENTIVI_SERVIZI_ID = 1;

	/** 
	 * Index of column descrizione_servizio
	 */
	protected static final int COLUMN_DESCRIZIONE_SERVIZIO = 2;

	/** 
	 * Index of column preventivi_id
	 */
	protected static final int COLUMN_PREVENTIVI_ID = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column preventivi_servizi_id
	 */
	protected static final int PK_COLUMN_PREVENTIVI_SERVIZI_ID = 1;

	/** 
	 * Inserts a new row in the preventivi_servizi table.
	 */
	public PreventiviServiziPk insert(PreventiviServizi dto) throws PreventiviServiziDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( "SELECT nextval('seq_preventivi')" );
			rs = stmt.executeQuery();
			if (rs.next()) {
				dto.setPreventiviServiziId( rs.getLong( 1 ) );
				rs.close();
				stmt.close();
			}
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getPreventiviServiziId() );
			stmt.setString( index++, dto.getDescrizioneServizio() );
			if (dto.isPreventiviIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setLong( index++, dto.getPreventiviId() );
			}
		
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PreventiviServiziDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the preventivi_servizi table.
	 */
	public void update(PreventiviServiziPk pk, PreventiviServizi dto) throws PreventiviServiziDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getPreventiviServiziId() );
			stmt.setString( index++, dto.getDescrizioneServizio() );
			if (dto.isPreventiviIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setLong( index++, dto.getPreventiviId() );
			}
		
			stmt.setLong( 4, pk.getPreventiviServiziId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PreventiviServiziDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the preventivi_servizi table.
	 */
	public void delete(PreventiviServiziPk pk) throws PreventiviServiziDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getPreventiviServiziId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PreventiviServiziDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the preventivi_servizi table that matches the specified primary-key value.
	 */
	public PreventiviServizi findByPrimaryKey(PreventiviServiziPk pk) throws PreventiviServiziDaoException
	{
		return findByPrimaryKey( pk.getPreventiviServiziId() );
	}

	/** 
	 * Returns all rows from the preventivi_servizi table that match the criteria 'preventivi_servizi_id = :preventiviServiziId'.
	 */
	public PreventiviServizi findByPrimaryKey(long preventiviServiziId) throws PreventiviServiziDaoException
	{
		PreventiviServizi ret[] = findByDynamicSelect( SQL_SELECT + " WHERE preventivi_servizi_id = ?", new Object[] {  new Long(preventiviServiziId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the preventivi_servizi table that match the criteria ''.
	 */
	public PreventiviServizi[] findAll() throws PreventiviServiziDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY preventivi_servizi_id", null );
	}

	/** 
	 * Returns all rows from the preventivi_servizi table that match the criteria 'preventivi_id = :preventiviId'.
	 */
	public PreventiviServizi[] findByPreventivi(long preventiviId) throws PreventiviServiziDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE preventivi_id = ?", new Object[] {  new Long(preventiviId) } );
	}

	/** 
	 * Returns all rows from the preventivi_servizi table that match the criteria 'preventivi_servizi_id = :preventiviServiziId'.
	 */
	public PreventiviServizi[] findWherePreventiviServiziIdEquals(long preventiviServiziId) throws PreventiviServiziDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE preventivi_servizi_id = ? ORDER BY preventivi_servizi_id", new Object[] {  new Long(preventiviServiziId) } );
	}

	/** 
	 * Returns all rows from the preventivi_servizi table that match the criteria 'descrizione_servizio = :descrizioneServizio'.
	 */
	public PreventiviServizi[] findWhereDescrizioneServizioEquals(String descrizioneServizio) throws PreventiviServiziDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE descrizione_servizio = ? ORDER BY descrizione_servizio", new Object[] { descrizioneServizio } );
	}

	/** 
	 * Returns all rows from the preventivi_servizi table that match the criteria 'preventivi_id = :preventiviId'.
	 */
	public PreventiviServizi[] findWherePreventiviIdEquals(long preventiviId) throws PreventiviServiziDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE preventivi_id = ? ORDER BY preventivi_id", new Object[] {  new Long(preventiviId) } );
	}

	/**
	 * Method 'PreventiviServiziDaoImpl'
	 * 
	 */
	public PreventiviServiziDaoImpl()
	{
	}

	/**
	 * Method 'PreventiviServiziDaoImpl'
	 * 
	 * @param userConn
	 */
	public PreventiviServiziDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "preventivi_servizi";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected PreventiviServizi fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			PreventiviServizi dto = new PreventiviServizi();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected PreventiviServizi[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			PreventiviServizi dto = new PreventiviServizi();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		PreventiviServizi ret[] = new PreventiviServizi[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(PreventiviServizi dto, ResultSet rs) throws SQLException
	{
		dto.setPreventiviServiziId( rs.getLong( COLUMN_PREVENTIVI_SERVIZI_ID ) );
		dto.setDescrizioneServizio( rs.getString( COLUMN_DESCRIZIONE_SERVIZIO ) );
		dto.setPreventiviId( rs.getLong( COLUMN_PREVENTIVI_ID ) );
		if (rs.wasNull()) {
			dto.setPreventiviIdNull( true );
		}
		
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(PreventiviServizi dto)
	{
	}

	/** 
	 * Returns all rows from the preventivi_servizi table that match the specified arbitrary SQL statement
	 */
	public PreventiviServizi[] findByDynamicSelect(String sql, Object[] sqlParams) throws PreventiviServiziDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PreventiviServiziDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the preventivi_servizi table that match the specified arbitrary SQL statement
	 */
	public PreventiviServizi[] findByDynamicWhere(String sql, Object[] sqlParams) throws PreventiviServiziDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new PreventiviServiziDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
