/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.jdbc;

import com.mysecretwish.dao.*;
import com.mysecretwish.factory.*;
import com.mysecretwish.dto.*;
import com.mysecretwish.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class StrutturaIndicazioniDaoImpl extends AbstractDAO implements StrutturaIndicazioniDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ind_id, ind_partenza, ind_indicazione, struttura_str_id FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ind_id, ind_partenza, ind_indicazione, struttura_str_id ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ind_id = ?, ind_partenza = ?, ind_indicazione = ?, struttura_str_id = ? WHERE ind_id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ind_id = ?";

	/** 
	 * Index of column ind_id
	 */
	protected static final int COLUMN_IND_ID = 1;

	/** 
	 * Index of column ind_partenza
	 */
	protected static final int COLUMN_IND_PARTENZA = 2;

	/** 
	 * Index of column ind_indicazione
	 */
	protected static final int COLUMN_IND_INDICAZIONE = 3;

	/** 
	 * Index of column struttura_str_id
	 */
	protected static final int COLUMN_STRUTTURA_STR_ID = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column ind_id
	 */
	protected static final int PK_COLUMN_IND_ID = 1;

	/** 
	 * Inserts a new row in the struttura_indicazioni table.
	 */
	public StrutturaIndicazioniPk insert(StrutturaIndicazioni dto) throws StrutturaIndicazioniDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( "SELECT nextval('seq_strutture')" );
			rs = stmt.executeQuery();
			if (rs.next()) {
				dto.setIndId( rs.getLong( 1 ) );
				rs.close();
				stmt.close();
			}
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getIndId() );
			stmt.setString( index++, dto.getIndPartenza() );
			stmt.setString( index++, dto.getIndIndicazione() );
			stmt.setLong( index++, dto.getStrutturaStrId() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StrutturaIndicazioniDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the struttura_indicazioni table.
	 */
	public void update(StrutturaIndicazioniPk pk, StrutturaIndicazioni dto) throws StrutturaIndicazioniDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getIndId() );
			stmt.setString( index++, dto.getIndPartenza() );
			stmt.setString( index++, dto.getIndIndicazione() );
			stmt.setLong( index++, dto.getStrutturaStrId() );
			stmt.setLong( 5, pk.getIndId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StrutturaIndicazioniDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the struttura_indicazioni table.
	 */
	public void delete(StrutturaIndicazioniPk pk) throws StrutturaIndicazioniDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getIndId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StrutturaIndicazioniDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the struttura_indicazioni table that matches the specified primary-key value.
	 */
	public StrutturaIndicazioni findByPrimaryKey(StrutturaIndicazioniPk pk) throws StrutturaIndicazioniDaoException
	{
		return findByPrimaryKey( pk.getIndId() );
	}

	/** 
	 * Returns all rows from the struttura_indicazioni table that match the criteria 'ind_id = :indId'.
	 */
	public StrutturaIndicazioni findByPrimaryKey(long indId) throws StrutturaIndicazioniDaoException
	{
		StrutturaIndicazioni ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ind_id = ?", new Object[] {  new Long(indId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the struttura_indicazioni table that match the criteria ''.
	 */
	public StrutturaIndicazioni[] findAll() throws StrutturaIndicazioniDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ind_id", null );
	}

	/** 
	 * Returns all rows from the struttura_indicazioni table that match the criteria 'struttura_str_id = :strutturaStrId'.
	 */
	public StrutturaIndicazioni[] findByStruttura(long strutturaStrId) throws StrutturaIndicazioniDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE struttura_str_id = ?", new Object[] {  new Long(strutturaStrId) } );
	}

	/** 
	 * Returns all rows from the struttura_indicazioni table that match the criteria 'ind_id = :indId'.
	 */
	public StrutturaIndicazioni[] findWhereIndIdEquals(long indId) throws StrutturaIndicazioniDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ind_id = ? ORDER BY ind_id", new Object[] {  new Long(indId) } );
	}

	/** 
	 * Returns all rows from the struttura_indicazioni table that match the criteria 'ind_partenza = :indPartenza'.
	 */
	public StrutturaIndicazioni[] findWhereIndPartenzaEquals(String indPartenza) throws StrutturaIndicazioniDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ind_partenza = ? ORDER BY ind_partenza", new Object[] { indPartenza } );
	}

	/** 
	 * Returns all rows from the struttura_indicazioni table that match the criteria 'ind_indicazione = :indIndicazione'.
	 */
	public StrutturaIndicazioni[] findWhereIndIndicazioneEquals(String indIndicazione) throws StrutturaIndicazioniDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ind_indicazione = ? ORDER BY ind_indicazione", new Object[] { indIndicazione } );
	}

	/** 
	 * Returns all rows from the struttura_indicazioni table that match the criteria 'struttura_str_id = :strutturaStrId'.
	 */
	public StrutturaIndicazioni[] findWhereStrutturaStrIdEquals(long strutturaStrId) throws StrutturaIndicazioniDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE struttura_str_id = ? ORDER BY struttura_str_id", new Object[] {  new Long(strutturaStrId) } );
	}

	/**
	 * Method 'StrutturaIndicazioniDaoImpl'
	 * 
	 */
	public StrutturaIndicazioniDaoImpl()
	{
	}

	/**
	 * Method 'StrutturaIndicazioniDaoImpl'
	 * 
	 * @param userConn
	 */
	public StrutturaIndicazioniDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "struttura_indicazioni";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected StrutturaIndicazioni fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			StrutturaIndicazioni dto = new StrutturaIndicazioni();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected StrutturaIndicazioni[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			StrutturaIndicazioni dto = new StrutturaIndicazioni();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		StrutturaIndicazioni ret[] = new StrutturaIndicazioni[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(StrutturaIndicazioni dto, ResultSet rs) throws SQLException
	{
		dto.setIndId( rs.getLong( COLUMN_IND_ID ) );
		dto.setIndPartenza( rs.getString( COLUMN_IND_PARTENZA ) );
		dto.setIndIndicazione( rs.getString( COLUMN_IND_INDICAZIONE ) );
		dto.setStrutturaStrId( rs.getLong( COLUMN_STRUTTURA_STR_ID ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(StrutturaIndicazioni dto)
	{
	}

	/** 
	 * Returns all rows from the struttura_indicazioni table that match the specified arbitrary SQL statement
	 */
	public StrutturaIndicazioni[] findByDynamicSelect(String sql, Object[] sqlParams) throws StrutturaIndicazioniDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StrutturaIndicazioniDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the struttura_indicazioni table that match the specified arbitrary SQL statement
	 */
	public StrutturaIndicazioni[] findByDynamicWhere(String sql, Object[] sqlParams) throws StrutturaIndicazioniDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StrutturaIndicazioniDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
