/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.jdbc;

import com.mysecretwish.dao.*;
import com.mysecretwish.factory.*;
import com.mysecretwish.dto.*;
import com.mysecretwish.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class TipologiaCamereDaoImpl extends AbstractDAO implements TipologiaCamereDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT tpc_id, tpc_descrizione FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( tpc_id, tpc_descrizione ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET tpc_id = ?, tpc_descrizione = ? WHERE tpc_id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE tpc_id = ?";

	/** 
	 * Index of column tpc_id
	 */
	protected static final int COLUMN_TPC_ID = 1;

	/** 
	 * Index of column tpc_descrizione
	 */
	protected static final int COLUMN_TPC_DESCRIZIONE = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column tpc_id
	 */
	protected static final int PK_COLUMN_TPC_ID = 1;

	/** 
	 * Inserts a new row in the tipologia_camere table.
	 */
	public TipologiaCamerePk insert(TipologiaCamere dto) throws TipologiaCamereDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( "SELECT nextval('seq_tabelle_dominio')" );
			rs = stmt.executeQuery();
			if (rs.next()) {
				dto.setTpcId( rs.getLong( 1 ) );
				rs.close();
				stmt.close();
			}
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getTpcId() );
			stmt.setString( index++, dto.getTpcDescrizione() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipologiaCamereDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the tipologia_camere table.
	 */
	public void update(TipologiaCamerePk pk, TipologiaCamere dto) throws TipologiaCamereDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getTpcId() );
			stmt.setString( index++, dto.getTpcDescrizione() );
			stmt.setLong( 3, pk.getTpcId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipologiaCamereDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the tipologia_camere table.
	 */
	public void delete(TipologiaCamerePk pk) throws TipologiaCamereDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getTpcId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipologiaCamereDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the tipologia_camere table that matches the specified primary-key value.
	 */
	public TipologiaCamere findByPrimaryKey(TipologiaCamerePk pk) throws TipologiaCamereDaoException
	{
		return findByPrimaryKey( pk.getTpcId() );
	}

	/** 
	 * Returns all rows from the tipologia_camere table that match the criteria 'tpc_id = :tpcId'.
	 */
	public TipologiaCamere findByPrimaryKey(long tpcId) throws TipologiaCamereDaoException
	{
		TipologiaCamere ret[] = findByDynamicSelect( SQL_SELECT + " WHERE tpc_id = ?", new Object[] {  new Long(tpcId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the tipologia_camere table that match the criteria ''.
	 */
	public TipologiaCamere[] findAll() throws TipologiaCamereDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY tpc_id", null );
	}

	/** 
	 * Returns all rows from the tipologia_camere table that match the criteria 'tpc_id = :tpcId'.
	 */
	public TipologiaCamere[] findWhereTpcIdEquals(long tpcId) throws TipologiaCamereDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE tpc_id = ? ORDER BY tpc_id", new Object[] {  new Long(tpcId) } );
	}

	/** 
	 * Returns all rows from the tipologia_camere table that match the criteria 'tpc_descrizione = :tpcDescrizione'.
	 */
	public TipologiaCamere[] findWhereTpcDescrizioneEquals(String tpcDescrizione) throws TipologiaCamereDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE tpc_descrizione = ? ORDER BY tpc_descrizione", new Object[] { tpcDescrizione } );
	}

	/**
	 * Method 'TipologiaCamereDaoImpl'
	 * 
	 */
	public TipologiaCamereDaoImpl()
	{
	}

	/**
	 * Method 'TipologiaCamereDaoImpl'
	 * 
	 * @param userConn
	 */
	public TipologiaCamereDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "tipologia_camere";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected TipologiaCamere fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			TipologiaCamere dto = new TipologiaCamere();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected TipologiaCamere[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			TipologiaCamere dto = new TipologiaCamere();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		TipologiaCamere ret[] = new TipologiaCamere[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(TipologiaCamere dto, ResultSet rs) throws SQLException
	{
		dto.setTpcId( rs.getLong( COLUMN_TPC_ID ) );
		dto.setTpcDescrizione( rs.getString( COLUMN_TPC_DESCRIZIONE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(TipologiaCamere dto)
	{
	}

	/** 
	 * Returns all rows from the tipologia_camere table that match the specified arbitrary SQL statement
	 */
	public TipologiaCamere[] findByDynamicSelect(String sql, Object[] sqlParams) throws TipologiaCamereDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipologiaCamereDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the tipologia_camere table that match the specified arbitrary SQL statement
	 */
	public TipologiaCamere[] findByDynamicWhere(String sql, Object[] sqlParams) throws TipologiaCamereDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipologiaCamereDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
