/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.jdbc;

import com.mysecretwish.dao.*;
import com.mysecretwish.factory.*;
import com.mysecretwish.dto.*;
import com.mysecretwish.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class TipologiaPromozioneDaoImpl extends AbstractDAO implements TipologiaPromozioneDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT tpp_id, tpp_descrizione FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( tpp_id, tpp_descrizione ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET tpp_id = ?, tpp_descrizione = ? WHERE tpp_id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE tpp_id = ?";

	/** 
	 * Index of column tpp_id
	 */
	protected static final int COLUMN_TPP_ID = 1;

	/** 
	 * Index of column tpp_descrizione
	 */
	protected static final int COLUMN_TPP_DESCRIZIONE = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column tpp_id
	 */
	protected static final int PK_COLUMN_TPP_ID = 1;

	/** 
	 * Inserts a new row in the tipologia_promozione table.
	 */
	public TipologiaPromozionePk insert(TipologiaPromozione dto) throws TipologiaPromozioneDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( "SELECT nextval('seq_tabelle_dominio')" );
			rs = stmt.executeQuery();
			if (rs.next()) {
				dto.setTppId( rs.getLong( 1 ) );
				rs.close();
				stmt.close();
			}
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getTppId() );
			stmt.setString( index++, dto.getTppDescrizione() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipologiaPromozioneDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the tipologia_promozione table.
	 */
	public void update(TipologiaPromozionePk pk, TipologiaPromozione dto) throws TipologiaPromozioneDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getTppId() );
			stmt.setString( index++, dto.getTppDescrizione() );
			stmt.setLong( 3, pk.getTppId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipologiaPromozioneDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the tipologia_promozione table.
	 */
	public void delete(TipologiaPromozionePk pk) throws TipologiaPromozioneDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getTppId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipologiaPromozioneDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the tipologia_promozione table that matches the specified primary-key value.
	 */
	public TipologiaPromozione findByPrimaryKey(TipologiaPromozionePk pk) throws TipologiaPromozioneDaoException
	{
		return findByPrimaryKey( pk.getTppId() );
	}

	/** 
	 * Returns all rows from the tipologia_promozione table that match the criteria 'tpp_id = :tppId'.
	 */
	public TipologiaPromozione findByPrimaryKey(long tppId) throws TipologiaPromozioneDaoException
	{
		TipologiaPromozione ret[] = findByDynamicSelect( SQL_SELECT + " WHERE tpp_id = ?", new Object[] {  new Long(tppId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the tipologia_promozione table that match the criteria ''.
	 */
	public TipologiaPromozione[] findAll() throws TipologiaPromozioneDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY tpp_id", null );
	}

	/** 
	 * Returns all rows from the tipologia_promozione table that match the criteria 'tpp_id = :tppId'.
	 */
	public TipologiaPromozione[] findWhereTppIdEquals(long tppId) throws TipologiaPromozioneDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE tpp_id = ? ORDER BY tpp_id", new Object[] {  new Long(tppId) } );
	}

	/** 
	 * Returns all rows from the tipologia_promozione table that match the criteria 'tpp_descrizione = :tppDescrizione'.
	 */
	public TipologiaPromozione[] findWhereTppDescrizioneEquals(String tppDescrizione) throws TipologiaPromozioneDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE tpp_descrizione = ? ORDER BY tpp_descrizione", new Object[] { tppDescrizione } );
	}

	/**
	 * Method 'TipologiaPromozioneDaoImpl'
	 * 
	 */
	public TipologiaPromozioneDaoImpl()
	{
	}

	/**
	 * Method 'TipologiaPromozioneDaoImpl'
	 * 
	 * @param userConn
	 */
	public TipologiaPromozioneDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "tipologia_promozione";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected TipologiaPromozione fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			TipologiaPromozione dto = new TipologiaPromozione();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected TipologiaPromozione[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			TipologiaPromozione dto = new TipologiaPromozione();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		TipologiaPromozione ret[] = new TipologiaPromozione[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(TipologiaPromozione dto, ResultSet rs) throws SQLException
	{
		dto.setTppId( rs.getLong( COLUMN_TPP_ID ) );
		dto.setTppDescrizione( rs.getString( COLUMN_TPP_DESCRIZIONE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(TipologiaPromozione dto)
	{
	}

	/** 
	 * Returns all rows from the tipologia_promozione table that match the specified arbitrary SQL statement
	 */
	public TipologiaPromozione[] findByDynamicSelect(String sql, Object[] sqlParams) throws TipologiaPromozioneDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipologiaPromozioneDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the tipologia_promozione table that match the specified arbitrary SQL statement
	 */
	public TipologiaPromozione[] findByDynamicWhere(String sql, Object[] sqlParams) throws TipologiaPromozioneDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TipologiaPromozioneDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
