/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dao;

import com.mysecretwish.dto.*;
import com.mysecretwish.exceptions.*;

public interface CamereDotazioniDao
{
	/** 
	 * Inserts a new row in the camere_dotazioni table.
	 */
	public CamereDotazioniPk insert(CamereDotazioni dto) throws CamereDotazioniDaoException;

	/** 
	 * Updates a single row in the camere_dotazioni table.
	 */
	public void update(CamereDotazioniPk pk, CamereDotazioni dto) throws CamereDotazioniDaoException;

	/** 
	 * Deletes a single row in the camere_dotazioni table.
	 */
	public void delete(CamereDotazioniPk pk) throws CamereDotazioniDaoException;

	/** 
	 * Returns the rows from the camere_dotazioni table that matches the specified primary-key value.
	 */
	public CamereDotazioni findByPrimaryKey(CamereDotazioniPk pk) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_id = :scdId'.
	 */
	public CamereDotazioni findByPrimaryKey(long scdId) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria ''.
	 */
	public CamereDotazioni[] findAll() throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'camere_cam_id = :camereCamId'.
	 */
	public CamereDotazioni[] findByCamere(long camereCamId) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_id = :scdId'.
	 */
	public CamereDotazioni[] findWhereScdIdEquals(long scdId) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_lettini_culle = :scdLettiniCulle'.
	 */
	public CamereDotazioni[] findWhereScdLettiniCulleEquals(String scdLettiniCulle) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_pisc_vista = :scdPiscVista'.
	 */
	public CamereDotazioni[] findWhereScdPiscVistaEquals(String scdPiscVista) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_appendiabiti = :scdAppendiabiti'.
	 */
	public CamereDotazioni[] findWhereScdAppendiabitiEquals(String scdAppendiabiti) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_pisc_ultimo_piano = :scdPiscUltimoPiano'.
	 */
	public CamereDotazioni[] findWhereScdPiscUltimoPianoEquals(String scdPiscUltimoPiano) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_stendibianc = :scdStendibianc'.
	 */
	public CamereDotazioni[] findWhereScdStendibiancEquals(String scdStendibianc) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_pisc_salata = :scdPiscSalata'.
	 */
	public CamereDotazioni[] findWhereScdPiscSalataEquals(String scdPiscSalata) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_letto_pieg = :scdLettoPieg'.
	 */
	public CamereDotazioni[] findWhereScdLettoPiegEquals(String scdLettoPieg) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_zona_acqua_bas = :scdZonaAcquaBas'.
	 */
	public CamereDotazioni[] findWhereScdZonaAcquaBasEquals(String scdZonaAcquaBas) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_divano_let = :scdDivanoLet'.
	 */
	public CamereDotazioni[] findWhereScdDivanoLetEquals(String scdDivanoLet) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_area_cond = :scdAreaCond'.
	 */
	public CamereDotazioni[] findWhereScdAreaCondEquals(String scdAreaCond) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_pattumiere = :scdPattumiere'.
	 */
	public CamereDotazioni[] findWhereScdPattumiereEquals(String scdPattumiere) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_pisc_uso_escl = :scdPiscUsoEscl'.
	 */
	public CamereDotazioni[] findWhereScdPiscUsoEsclEquals(String scdPiscUsoEscl) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_pisc_riscald = :scdPiscRiscald'.
	 */
	public CamereDotazioni[] findWhereScdPiscRiscaldEquals(String scdPiscRiscald) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_asciugatrice = :scdAsciugatrice'.
	 */
	public CamereDotazioni[] findWhereScdAsciugatriceEquals(String scdAsciugatrice) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_pisc_sfioro = :scdPiscSfioro'.
	 */
	public CamereDotazioni[] findWhereScdPiscSfioroEquals(String scdPiscSfioro) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_armadio = :scdArmadio'.
	 */
	public CamereDotazioni[] findWhereScdArmadioEquals(String scdArmadio) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_copert_pisc = :scdCopertPisc'.
	 */
	public CamereDotazioni[] findWhereScdCopertPiscEquals(String scdCopertPisc) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_moquette = :scdMoquette'.
	 */
	public CamereDotazioni[] findWhereScdMoquetteEquals(String scdMoquette) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_teli = :scdTeli'.
	 */
	public CamereDotazioni[] findWhereScdTeliEquals(String scdTeli) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_cab_armadio = :scdCabArmadio'.
	 */
	public CamereDotazioni[] findWhereScdCabArmadioEquals(String scdCabArmadio) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_vasc_imm_fred = :scdVascImmFred'.
	 */
	public CamereDotazioni[] findWhereScdVascImmFredEquals(String scdVascImmFred) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_letti_lung = :scdLettiLung'.
	 */
	public CamereDotazioni[] findWhereScdLettiLungEquals(String scdLettiLung) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_asciug_pisc = :scdAsciugPisc'.
	 */
	public CamereDotazioni[] findWhereScdAsciugPiscEquals(String scdAsciugPisc) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_ventilatore = :scdVentilatore'.
	 */
	public CamereDotazioni[] findWhereScdVentilatoreEquals(String scdVentilatore) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_camino = :scdCamino'.
	 */
	public CamereDotazioni[] findWhereScdCaminoEquals(String scdCamino) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_ingresso_ind = :scdIngressoInd'.
	 */
	public CamereDotazioni[] findWhereScdIngressoIndEquals(String scdIngressoInd) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_riscaldameno = :scdRiscaldameno'.
	 */
	public CamereDotazioni[] findWhereScdRiscaldamenoEquals(String scdRiscaldameno) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_cassaforte = :scdCassaforte'.
	 */
	public CamereDotazioni[] findWhereScdCassaforteEquals(String scdCassaforte) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_disp_cam_comunic = :scdDispCamComunic'.
	 */
	public CamereDotazioni[] findWhereScdDispCamComunicEquals(String scdDispCamComunic) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_divano = :scdDivano'.
	 */
	public CamereDotazioni[] findWhereScdDivanoEquals(String scdDivano) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_ferro_stiro = :scdFerroStiro'.
	 */
	public CamereDotazioni[] findWhereScdFerroStiroEquals(String scdFerroStiro) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_insonorizzazione = :scdInsonorizzazione'.
	 */
	public CamereDotazioni[] findWhereScdInsonorizzazioneEquals(String scdInsonorizzazione) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_asse_da_stiro = :scdAsseDaStiro'.
	 */
	public CamereDotazioni[] findWhereScdAsseDaStiroEquals(String scdAsseDaStiro) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_zona_giorn = :scdZonaGiorn'.
	 */
	public CamereDotazioni[] findWhereScdZonaGiornEquals(String scdZonaGiorn) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_vasca_idro = :scdVascaIdro'.
	 */
	public CamereDotazioni[] findWhereScdVascaIdroEquals(String scdVascaIdro) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_stirapant = :scdStirapant'.
	 */
	public CamereDotazioni[] findWhereScdStirapantEquals(String scdStirapant) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_zanzariera = :scdZanzariera'.
	 */
	public CamereDotazioni[] findWhereScdZanzarieraEquals(String scdZanzariera) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_lavatrice = :scdLavatrice'.
	 */
	public CamereDotazioni[] findWhereScdLavatriceEquals(String scdLavatrice) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_pavim_marmo = :scdPavimMarmo'.
	 */
	public CamereDotazioni[] findWhereScdPavimMarmoEquals(String scdPavimMarmo) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_parquet = :scdParquet'.
	 */
	public CamereDotazioni[] findWhereScdParquetEquals(String scdParquet) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_scrivania = :scdScrivania'.
	 */
	public CamereDotazioni[] findWhereScdScrivaniaEquals(String scdScrivania) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_pigiama = :scdPigiama'.
	 */
	public CamereDotazioni[] findWhereScdPigiamaEquals(String scdPigiama) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_sol_anallergiche = :scdSolAnallergiche'.
	 */
	public CamereDotazioni[] findWhereScdSolAnallergicheEquals(String scdSolAnallergiche) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_presa_letto = :scdPresaLetto'.
	 */
	public CamereDotazioni[] findWhereScdPresaLettoEquals(String scdPresaLetto) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_prod_pulizie = :scdProdPulizie'.
	 */
	public CamereDotazioni[] findWhereScdProdPulizieEquals(String scdProdPulizie) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_adattatore = :scdAdattatore'.
	 */
	public CamereDotazioni[] findWhereScdAdattatoreEquals(String scdAdattatore) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_coperte_elet = :scdCoperteElet'.
	 */
	public CamereDotazioni[] findWhereScdCoperteEletEquals(String scdCoperteElet) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_cuscino_piume = :scdCuscinoPiume'.
	 */
	public CamereDotazioni[] findWhereScdCuscinoPiumeEquals(String scdCuscinoPiume) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_cuscino_no_piume = :scdCuscinoNoPiume'.
	 */
	public CamereDotazioni[] findWhereScdCuscinoNoPiumeEquals(String scdCuscinoNoPiume) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'scd_cuscino_ipo = :scdCuscinoIpo'.
	 */
	public CamereDotazioni[] findWhereScdCuscinoIpoEquals(String scdCuscinoIpo) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the criteria 'camere_cam_id = :camereCamId'.
	 */
	public CamereDotazioni[] findWhereCamereCamIdEquals(long camereCamId) throws CamereDotazioniDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the camere_dotazioni table that match the specified arbitrary SQL statement
	 */
	public CamereDotazioni[] findByDynamicSelect(String sql, Object[] sqlParams) throws CamereDotazioniDaoException;

	/** 
	 * Returns all rows from the camere_dotazioni table that match the specified arbitrary SQL statement
	 */
	public CamereDotazioni[] findByDynamicWhere(String sql, Object[] sqlParams) throws CamereDotazioniDaoException;

}
