/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dao;

import com.mysecretwish.dto.*;
import com.mysecretwish.exceptions.*;

public interface StrutturaSpaBenessereDao
{
	/** 
	 * Inserts a new row in the struttura_spa_benessere table.
	 */
	public StrutturaSpaBenesserePk insert(StrutturaSpaBenessere dto) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Updates a single row in the struttura_spa_benessere table.
	 */
	public void update(StrutturaSpaBenesserePk pk, StrutturaSpaBenessere dto) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Deletes a single row in the struttura_spa_benessere table.
	 */
	public void delete(StrutturaSpaBenesserePk pk) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns the rows from the struttura_spa_benessere table that matches the specified primary-key value.
	 */
	public StrutturaSpaBenessere findByPrimaryKey(StrutturaSpaBenesserePk pk) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_id = :sspId'.
	 */
	public StrutturaSpaBenessere findByPrimaryKey(long sspId) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria ''.
	 */
	public StrutturaSpaBenessere[] findAll() throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'struttura_str_id = :strutturaStrId'.
	 */
	public StrutturaSpaBenessere[] findByStruttura(long strutturaStrId) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_id = :sspId'.
	 */
	public StrutturaSpaBenessere[] findWhereSspIdEquals(long sspId) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_spa_ben = :sspSpaBen'.
	 */
	public StrutturaSpaBenessere[] findWhereSspSpaBenEquals(String sspSpaBen) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_costo = :sspCosto'.
	 */
	public StrutturaSpaBenessere[] findWhereSspCostoEquals(float sspCosto) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_sauna = :sspSauna'.
	 */
	public StrutturaSpaBenessere[] findWhereSspSaunaEquals(String sspSauna) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_hammam = :sspHammam'.
	 */
	public StrutturaSpaBenessere[] findWhereSspHammamEquals(String sspHammam) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_vasca_idro = :sspVascaIdro'.
	 */
	public StrutturaSpaBenessere[] findWhereSspVascaIdroEquals(String sspVascaIdro) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_palestra = :sspPalestra'.
	 */
	public StrutturaSpaBenessere[] findWhereSspPalestraEquals(String sspPalestra) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_solarium = :sspSolarium'.
	 */
	public StrutturaSpaBenessere[] findWhereSspSolariumEquals(String sspSolarium) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_vasca_term = :sspVascaTerm'.
	 */
	public StrutturaSpaBenessere[] findWhereSspVascaTermEquals(String sspVascaTerm) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_massaggi = :sspMassaggi'.
	 */
	public StrutturaSpaBenessere[] findWhereSspMassaggiEquals(String sspMassaggi) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_costo_mass = :sspCostoMass'.
	 */
	public StrutturaSpaBenessere[] findWhereSspCostoMassEquals(float sspCostoMass) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_mass_schiena = :sspMassSchiena'.
	 */
	public StrutturaSpaBenessere[] findWhereSspMassSchienaEquals(String sspMassSchiena) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_mass_collo = :sspMassCollo'.
	 */
	public StrutturaSpaBenessere[] findWhereSspMassColloEquals(String sspMassCollo) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_mass_testa = :sspMassTesta'.
	 */
	public StrutturaSpaBenessere[] findWhereSspMassTestaEquals(String sspMassTesta) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_mass_coppia = :sspMassCoppia'.
	 */
	public StrutturaSpaBenessere[] findWhereSspMassCoppiaEquals(String sspMassCoppia) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_mass_corpo = :sspMassCorpo'.
	 */
	public StrutturaSpaBenessere[] findWhereSspMassCorpoEquals(String sspMassCorpo) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_mass_mani = :sspMassMani'.
	 */
	public StrutturaSpaBenessere[] findWhereSspMassManiEquals(String sspMassMani) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_vasca_com = :sspVascaCom'.
	 */
	public StrutturaSpaBenessere[] findWhereSspVascaComEquals(String sspVascaCom) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'ssp_vasca_aperto = :sspVascaAperto'.
	 */
	public StrutturaSpaBenessere[] findWhereSspVascaApertoEquals(String sspVascaAperto) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the criteria 'struttura_str_id = :strutturaStrId'.
	 */
	public StrutturaSpaBenessere[] findWhereStrutturaStrIdEquals(long strutturaStrId) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the specified arbitrary SQL statement
	 */
	public StrutturaSpaBenessere[] findByDynamicSelect(String sql, Object[] sqlParams) throws StrutturaSpaBenessereDaoException;

	/** 
	 * Returns all rows from the struttura_spa_benessere table that match the specified arbitrary SQL statement
	 */
	public StrutturaSpaBenessere[] findByDynamicWhere(String sql, Object[] sqlParams) throws StrutturaSpaBenessereDaoException;

}
