/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dao;

import com.mysecretwish.dto.*;
import com.mysecretwish.exceptions.*;

public interface TipologiaStrutturaDao
{
	/** 
	 * Inserts a new row in the tipologia_struttura table.
	 */
	public TipologiaStrutturaPk insert(TipologiaStruttura dto) throws TipologiaStrutturaDaoException;

	/** 
	 * Updates a single row in the tipologia_struttura table.
	 */
	public void update(TipologiaStrutturaPk pk, TipologiaStruttura dto) throws TipologiaStrutturaDaoException;

	/** 
	 * Deletes a single row in the tipologia_struttura table.
	 */
	public void delete(TipologiaStrutturaPk pk) throws TipologiaStrutturaDaoException;

	/** 
	 * Returns the rows from the tipologia_struttura table that matches the specified primary-key value.
	 */
	public TipologiaStruttura findByPrimaryKey(TipologiaStrutturaPk pk) throws TipologiaStrutturaDaoException;

	/** 
	 * Returns all rows from the tipologia_struttura table that match the criteria 'id = :id'.
	 */
	public TipologiaStruttura findByPrimaryKey(long id) throws TipologiaStrutturaDaoException;

	/** 
	 * Returns all rows from the tipologia_struttura table that match the criteria ''.
	 */
	public TipologiaStruttura[] findAll() throws TipologiaStrutturaDaoException;

	/** 
	 * Returns all rows from the tipologia_struttura table that match the criteria 'id = :id'.
	 */
	public TipologiaStruttura[] findWhereIdEquals(long id) throws TipologiaStrutturaDaoException;

	/** 
	 * Returns all rows from the tipologia_struttura table that match the criteria 'descrizione = :descrizione'.
	 */
	public TipologiaStruttura[] findWhereDescrizioneEquals(String descrizione) throws TipologiaStrutturaDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the tipologia_struttura table that match the specified arbitrary SQL statement
	 */
	public TipologiaStruttura[] findByDynamicSelect(String sql, Object[] sqlParams) throws TipologiaStrutturaDaoException;

	/** 
	 * Returns all rows from the tipologia_struttura table that match the specified arbitrary SQL statement
	 */
	public TipologiaStruttura[] findByDynamicWhere(String sql, Object[] sqlParams) throws TipologiaStrutturaDaoException;

}
