/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dto;

import com.mysecretwish.dao.*;
import com.mysecretwish.factory.*;
import com.mysecretwish.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class CamereAccessibilita implements Serializable
{
	/** 
	 * This attribute maps to the column sca_id in the camere_accessibilita table.
	 */
	protected long scaId;

	/** 
	 * This attribute maps to the column sca_ascensore in the camere_accessibilita table.
	 */
	protected String scaAscensore;

	/** 
	 * This attribute maps to the column sca_piano_ter in the camere_accessibilita table.
	 */
	protected String scaPianoTer;

	/** 
	 * This attribute maps to the column sca_sedia_rot in the camere_accessibilita table.
	 */
	protected String scaSediaRot;

	/** 
	 * This attribute maps to the column sca_piani_sup_asc in the camere_accessibilita table.
	 */
	protected String scaPianiSupAsc;

	/** 
	 * This attribute maps to the column sca_piani_sup_scale in the camere_accessibilita table.
	 */
	protected String scaPianiSupScale;

	/** 
	 * This attribute maps to the column sca_edif_indip in the camere_accessibilita table.
	 */
	protected String scaEdifIndip;

	/** 
	 * This attribute maps to the column sca_app_priv in the camere_accessibilita table.
	 */
	protected String scaAppPriv;

	/** 
	 * This attribute maps to the column sca_semi_ind in the camere_accessibilita table.
	 */
	protected String scaSemiInd;

	/** 
	 * This attribute maps to the column camere_cam_id in the camere_accessibilita table.
	 */
	protected long camereCamId;

	/**
	 * Method 'CamereAccessibilita'
	 * 
	 */
	public CamereAccessibilita()
	{
	}

	/**
	 * Method 'getScaId'
	 * 
	 * @return long
	 */
	public long getScaId()
	{
		return scaId;
	}

	/**
	 * Method 'setScaId'
	 * 
	 * @param scaId
	 */
	public void setScaId(long scaId)
	{
		this.scaId = scaId;
	}

	/**
	 * Method 'getScaAscensore'
	 * 
	 * @return String
	 */
	public String getScaAscensore()
	{
		return scaAscensore;
	}

	/**
	 * Method 'setScaAscensore'
	 * 
	 * @param scaAscensore
	 */
	public void setScaAscensore(String scaAscensore)
	{
		this.scaAscensore = scaAscensore;
	}

	/**
	 * Method 'getScaPianoTer'
	 * 
	 * @return String
	 */
	public String getScaPianoTer()
	{
		return scaPianoTer;
	}

	/**
	 * Method 'setScaPianoTer'
	 * 
	 * @param scaPianoTer
	 */
	public void setScaPianoTer(String scaPianoTer)
	{
		this.scaPianoTer = scaPianoTer;
	}

	/**
	 * Method 'getScaSediaRot'
	 * 
	 * @return String
	 */
	public String getScaSediaRot()
	{
		return scaSediaRot;
	}

	/**
	 * Method 'setScaSediaRot'
	 * 
	 * @param scaSediaRot
	 */
	public void setScaSediaRot(String scaSediaRot)
	{
		this.scaSediaRot = scaSediaRot;
	}

	/**
	 * Method 'getScaPianiSupAsc'
	 * 
	 * @return String
	 */
	public String getScaPianiSupAsc()
	{
		return scaPianiSupAsc;
	}

	/**
	 * Method 'setScaPianiSupAsc'
	 * 
	 * @param scaPianiSupAsc
	 */
	public void setScaPianiSupAsc(String scaPianiSupAsc)
	{
		this.scaPianiSupAsc = scaPianiSupAsc;
	}

	/**
	 * Method 'getScaPianiSupScale'
	 * 
	 * @return String
	 */
	public String getScaPianiSupScale()
	{
		return scaPianiSupScale;
	}

	/**
	 * Method 'setScaPianiSupScale'
	 * 
	 * @param scaPianiSupScale
	 */
	public void setScaPianiSupScale(String scaPianiSupScale)
	{
		this.scaPianiSupScale = scaPianiSupScale;
	}

	/**
	 * Method 'getScaEdifIndip'
	 * 
	 * @return String
	 */
	public String getScaEdifIndip()
	{
		return scaEdifIndip;
	}

	/**
	 * Method 'setScaEdifIndip'
	 * 
	 * @param scaEdifIndip
	 */
	public void setScaEdifIndip(String scaEdifIndip)
	{
		this.scaEdifIndip = scaEdifIndip;
	}

	/**
	 * Method 'getScaAppPriv'
	 * 
	 * @return String
	 */
	public String getScaAppPriv()
	{
		return scaAppPriv;
	}

	/**
	 * Method 'setScaAppPriv'
	 * 
	 * @param scaAppPriv
	 */
	public void setScaAppPriv(String scaAppPriv)
	{
		this.scaAppPriv = scaAppPriv;
	}

	/**
	 * Method 'getScaSemiInd'
	 * 
	 * @return String
	 */
	public String getScaSemiInd()
	{
		return scaSemiInd;
	}

	/**
	 * Method 'setScaSemiInd'
	 * 
	 * @param scaSemiInd
	 */
	public void setScaSemiInd(String scaSemiInd)
	{
		this.scaSemiInd = scaSemiInd;
	}

	/**
	 * Method 'getCamereCamId'
	 * 
	 * @return long
	 */
	public long getCamereCamId()
	{
		return camereCamId;
	}

	/**
	 * Method 'setCamereCamId'
	 * 
	 * @param camereCamId
	 */
	public void setCamereCamId(long camereCamId)
	{
		this.camereCamId = camereCamId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CamereAccessibilita)) {
			return false;
		}
		
		final CamereAccessibilita _cast = (CamereAccessibilita) _other;
		if (scaId != _cast.scaId) {
			return false;
		}
		
		if (scaAscensore == null ? _cast.scaAscensore != scaAscensore : !scaAscensore.equals( _cast.scaAscensore )) {
			return false;
		}
		
		if (scaPianoTer == null ? _cast.scaPianoTer != scaPianoTer : !scaPianoTer.equals( _cast.scaPianoTer )) {
			return false;
		}
		
		if (scaSediaRot == null ? _cast.scaSediaRot != scaSediaRot : !scaSediaRot.equals( _cast.scaSediaRot )) {
			return false;
		}
		
		if (scaPianiSupAsc == null ? _cast.scaPianiSupAsc != scaPianiSupAsc : !scaPianiSupAsc.equals( _cast.scaPianiSupAsc )) {
			return false;
		}
		
		if (scaPianiSupScale == null ? _cast.scaPianiSupScale != scaPianiSupScale : !scaPianiSupScale.equals( _cast.scaPianiSupScale )) {
			return false;
		}
		
		if (scaEdifIndip == null ? _cast.scaEdifIndip != scaEdifIndip : !scaEdifIndip.equals( _cast.scaEdifIndip )) {
			return false;
		}
		
		if (scaAppPriv == null ? _cast.scaAppPriv != scaAppPriv : !scaAppPriv.equals( _cast.scaAppPriv )) {
			return false;
		}
		
		if (scaSemiInd == null ? _cast.scaSemiInd != scaSemiInd : !scaSemiInd.equals( _cast.scaSemiInd )) {
			return false;
		}
		
		if (camereCamId != _cast.camereCamId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (scaId ^ (scaId >>> 32));
		if (scaAscensore != null) {
			_hashCode = 29 * _hashCode + scaAscensore.hashCode();
		}
		
		if (scaPianoTer != null) {
			_hashCode = 29 * _hashCode + scaPianoTer.hashCode();
		}
		
		if (scaSediaRot != null) {
			_hashCode = 29 * _hashCode + scaSediaRot.hashCode();
		}
		
		if (scaPianiSupAsc != null) {
			_hashCode = 29 * _hashCode + scaPianiSupAsc.hashCode();
		}
		
		if (scaPianiSupScale != null) {
			_hashCode = 29 * _hashCode + scaPianiSupScale.hashCode();
		}
		
		if (scaEdifIndip != null) {
			_hashCode = 29 * _hashCode + scaEdifIndip.hashCode();
		}
		
		if (scaAppPriv != null) {
			_hashCode = 29 * _hashCode + scaAppPriv.hashCode();
		}
		
		if (scaSemiInd != null) {
			_hashCode = 29 * _hashCode + scaSemiInd.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (camereCamId ^ (camereCamId >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CamereAccessibilitaPk
	 */
	public CamereAccessibilitaPk createPk()
	{
		return new CamereAccessibilitaPk(scaId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mysecretwish.dto.CamereAccessibilita: " );
		ret.append( "scaId=" + scaId );
		ret.append( ", scaAscensore=" + scaAscensore );
		ret.append( ", scaPianoTer=" + scaPianoTer );
		ret.append( ", scaSediaRot=" + scaSediaRot );
		ret.append( ", scaPianiSupAsc=" + scaPianiSupAsc );
		ret.append( ", scaPianiSupScale=" + scaPianiSupScale );
		ret.append( ", scaEdifIndip=" + scaEdifIndip );
		ret.append( ", scaAppPriv=" + scaAppPriv );
		ret.append( ", scaSemiInd=" + scaSemiInd );
		ret.append( ", camereCamId=" + camereCamId );
		return ret.toString();
	}

}
