/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dto;

import com.mysecretwish.dao.*;
import com.mysecretwish.factory.*;
import com.mysecretwish.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class PrenotazioneServizi implements Serializable
{
	/** 
	 * This attribute maps to the column prenotazione_servizi_id in the prenotazione_servizi table.
	 */
	protected long prenotazioneServiziId;

	/** 
	 * This attribute maps to the column descrizione_servizio in the prenotazione_servizi table.
	 */
	protected String descrizioneServizio;

	/** 
	 * This attribute maps to the column prenotazione_id in the prenotazione_servizi table.
	 */
	protected long prenotazioneId;

	/** 
	 * This attribute represents whether the primitive attribute prenotazioneId is null.
	 */
	protected boolean prenotazioneIdNull = true;

	/**
	 * Method 'PrenotazioneServizi'
	 * 
	 */
	public PrenotazioneServizi()
	{
	}

	/**
	 * Method 'getPrenotazioneServiziId'
	 * 
	 * @return long
	 */
	public long getPrenotazioneServiziId()
	{
		return prenotazioneServiziId;
	}

	/**
	 * Method 'setPrenotazioneServiziId'
	 * 
	 * @param prenotazioneServiziId
	 */
	public void setPrenotazioneServiziId(long prenotazioneServiziId)
	{
		this.prenotazioneServiziId = prenotazioneServiziId;
	}

	/**
	 * Method 'getDescrizioneServizio'
	 * 
	 * @return String
	 */
	public String getDescrizioneServizio()
	{
		return descrizioneServizio;
	}

	/**
	 * Method 'setDescrizioneServizio'
	 * 
	 * @param descrizioneServizio
	 */
	public void setDescrizioneServizio(String descrizioneServizio)
	{
		this.descrizioneServizio = descrizioneServizio;
	}

	/**
	 * Method 'getPrenotazioneId'
	 * 
	 * @return long
	 */
	public long getPrenotazioneId()
	{
		return prenotazioneId;
	}

	/**
	 * Method 'setPrenotazioneId'
	 * 
	 * @param prenotazioneId
	 */
	public void setPrenotazioneId(long prenotazioneId)
	{
		this.prenotazioneId = prenotazioneId;
		this.prenotazioneIdNull = false;
	}

	/**
	 * Method 'setPrenotazioneIdNull'
	 * 
	 * @param value
	 */
	public void setPrenotazioneIdNull(boolean value)
	{
		this.prenotazioneIdNull = value;
	}

	/**
	 * Method 'isPrenotazioneIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isPrenotazioneIdNull()
	{
		return prenotazioneIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PrenotazioneServizi)) {
			return false;
		}
		
		final PrenotazioneServizi _cast = (PrenotazioneServizi) _other;
		if (prenotazioneServiziId != _cast.prenotazioneServiziId) {
			return false;
		}
		
		if (descrizioneServizio == null ? _cast.descrizioneServizio != descrizioneServizio : !descrizioneServizio.equals( _cast.descrizioneServizio )) {
			return false;
		}
		
		if (prenotazioneId != _cast.prenotazioneId) {
			return false;
		}
		
		if (prenotazioneIdNull != _cast.prenotazioneIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (prenotazioneServiziId ^ (prenotazioneServiziId >>> 32));
		if (descrizioneServizio != null) {
			_hashCode = 29 * _hashCode + descrizioneServizio.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (prenotazioneId ^ (prenotazioneId >>> 32));
		_hashCode = 29 * _hashCode + (prenotazioneIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PrenotazioneServiziPk
	 */
	public PrenotazioneServiziPk createPk()
	{
		return new PrenotazioneServiziPk(prenotazioneServiziId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mysecretwish.dto.PrenotazioneServizi: " );
		ret.append( "prenotazioneServiziId=" + prenotazioneServiziId );
		ret.append( ", descrizioneServizio=" + descrizioneServizio );
		ret.append( ", prenotazioneId=" + prenotazioneId );
		return ret.toString();
	}

}
