/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dto;

import com.mysecretwish.dao.*;
import com.mysecretwish.factory.*;
import com.mysecretwish.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class StrutturaTasse implements Serializable
{
	/** 
	 * This attribute maps to the column tas_id in the struttura_tasse table.
	 */
	protected long tasId;

	/** 
	 * This attribute maps to the column tas_nome in the struttura_tasse table.
	 */
	protected String tasNome;

	/** 
	 * This attribute maps to the column tas_costo in the struttura_tasse table.
	 */
	protected float tasCosto;

	/** 
	 * This attribute maps to the column struttura_str_id in the struttura_tasse table.
	 */
	protected long strutturaStrId;

	/**
	 * Method 'StrutturaTasse'
	 * 
	 */
	public StrutturaTasse()
	{
	}

	/**
	 * Method 'getTasId'
	 * 
	 * @return long
	 */
	public long getTasId()
	{
		return tasId;
	}

	/**
	 * Method 'setTasId'
	 * 
	 * @param tasId
	 */
	public void setTasId(long tasId)
	{
		this.tasId = tasId;
	}

	/**
	 * Method 'getTasNome'
	 * 
	 * @return String
	 */
	public String getTasNome()
	{
		return tasNome;
	}

	/**
	 * Method 'setTasNome'
	 * 
	 * @param tasNome
	 */
	public void setTasNome(String tasNome)
	{
		this.tasNome = tasNome;
	}

	/**
	 * Method 'getTasCosto'
	 * 
	 * @return float
	 */
	public float getTasCosto()
	{
		return tasCosto;
	}

	/**
	 * Method 'setTasCosto'
	 * 
	 * @param tasCosto
	 */
	public void setTasCosto(float tasCosto)
	{
		this.tasCosto = tasCosto;
	}

	/**
	 * Method 'getStrutturaStrId'
	 * 
	 * @return long
	 */
	public long getStrutturaStrId()
	{
		return strutturaStrId;
	}

	/**
	 * Method 'setStrutturaStrId'
	 * 
	 * @param strutturaStrId
	 */
	public void setStrutturaStrId(long strutturaStrId)
	{
		this.strutturaStrId = strutturaStrId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof StrutturaTasse)) {
			return false;
		}
		
		final StrutturaTasse _cast = (StrutturaTasse) _other;
		if (tasId != _cast.tasId) {
			return false;
		}
		
		if (tasNome == null ? _cast.tasNome != tasNome : !tasNome.equals( _cast.tasNome )) {
			return false;
		}
		
		if (tasCosto != _cast.tasCosto) {
			return false;
		}
		
		if (strutturaStrId != _cast.strutturaStrId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (tasId ^ (tasId >>> 32));
		if (tasNome != null) {
			_hashCode = 29 * _hashCode + tasNome.hashCode();
		}
		
		_hashCode = 29 * _hashCode + Float.floatToIntBits(tasCosto);
		_hashCode = 29 * _hashCode + (int) (strutturaStrId ^ (strutturaStrId >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return StrutturaTassePk
	 */
	public StrutturaTassePk createPk()
	{
		return new StrutturaTassePk(tasId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mysecretwish.dto.StrutturaTasse: " );
		ret.append( "tasId=" + tasId );
		ret.append( ", tasNome=" + tasNome );
		ret.append( ", tasCosto=" + tasCosto );
		ret.append( ", strutturaStrId=" + strutturaStrId );
		return ret.toString();
	}

}
