/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the struttura_piscine table.
 */
public class StrutturaPiscinePk implements Serializable
{
	protected long spiId;

	/** 
	 * This attribute represents whether the primitive attribute spiId is null.
	 */
	protected boolean spiIdNull;

	/** 
	 * Sets the value of spiId
	 */
	public void setSpiId(long spiId)
	{
		this.spiId = spiId;
	}

	/** 
	 * Gets the value of spiId
	 */
	public long getSpiId()
	{
		return spiId;
	}

	/**
	 * Method 'StrutturaPiscinePk'
	 * 
	 */
	public StrutturaPiscinePk()
	{
	}

	/**
	 * Method 'StrutturaPiscinePk'
	 * 
	 * @param spiId
	 */
	public StrutturaPiscinePk(final long spiId)
	{
		this.spiId = spiId;
	}

	/** 
	 * Sets the value of spiIdNull
	 */
	public void setSpiIdNull(boolean spiIdNull)
	{
		this.spiIdNull = spiIdNull;
	}

	/** 
	 * Gets the value of spiIdNull
	 */
	public boolean isSpiIdNull()
	{
		return spiIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof StrutturaPiscinePk)) {
			return false;
		}
		
		final StrutturaPiscinePk _cast = (StrutturaPiscinePk) _other;
		if (spiId != _cast.spiId) {
			return false;
		}
		
		if (spiIdNull != _cast.spiIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (spiId ^ (spiId >>> 32));
		_hashCode = 29 * _hashCode + (spiIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mysecretwish.dto.StrutturaPiscinePk: " );
		ret.append( "spiId=" + spiId );
		return ret.toString();
	}

}
