/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the struttura_spa_benessere table.
 */
public class StrutturaSpaBenesserePk implements Serializable
{
	protected long sspId;

	/** 
	 * This attribute represents whether the primitive attribute sspId is null.
	 */
	protected boolean sspIdNull;

	/** 
	 * Sets the value of sspId
	 */
	public void setSspId(long sspId)
	{
		this.sspId = sspId;
	}

	/** 
	 * Gets the value of sspId
	 */
	public long getSspId()
	{
		return sspId;
	}

	/**
	 * Method 'StrutturaSpaBenesserePk'
	 * 
	 */
	public StrutturaSpaBenesserePk()
	{
	}

	/**
	 * Method 'StrutturaSpaBenesserePk'
	 * 
	 * @param sspId
	 */
	public StrutturaSpaBenesserePk(final long sspId)
	{
		this.sspId = sspId;
	}

	/** 
	 * Sets the value of sspIdNull
	 */
	public void setSspIdNull(boolean sspIdNull)
	{
		this.sspIdNull = sspIdNull;
	}

	/** 
	 * Gets the value of sspIdNull
	 */
	public boolean isSspIdNull()
	{
		return sspIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof StrutturaSpaBenesserePk)) {
			return false;
		}
		
		final StrutturaSpaBenesserePk _cast = (StrutturaSpaBenesserePk) _other;
		if (sspId != _cast.sspId) {
			return false;
		}
		
		if (sspIdNull != _cast.sspIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (sspId ^ (sspId >>> 32));
		_hashCode = 29 * _hashCode + (sspIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mysecretwish.dto.StrutturaSpaBenesserePk: " );
		ret.append( "sspId=" + sspId );
		return ret.toString();
	}

}
