/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dto;

import com.mysecretwish.dao.*;
import com.mysecretwish.factory.*;
import com.mysecretwish.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class StrutturaCostiAgg implements Serializable
{
	/** 
	 * This attribute maps to the column sca_id in the struttura_costi_agg table.
	 */
	protected long scaId;

	/** 
	 * This attribute maps to the column sca_dep_cauzion in the struttura_costi_agg table.
	 */
	protected String scaDepCauzion;

	/** 
	 * This attribute maps to the column sca_inc_prezzo in the struttura_costi_agg table.
	 */
	protected String scaIncPrezzo;

	/** 
	 * This attribute maps to the column sca_importo in the struttura_costi_agg table.
	 */
	protected float scaImporto;

	/** 
	 * This attribute maps to the column struttura_str_id in the struttura_costi_agg table.
	 */
	protected long strutturaStrId;

	/** 
	 * This attribute maps to the column sca_tipo_costo in the struttura_costi_agg table.
	 */
	protected long scaTipoCosto;

	/** 
	 * This attribute represents whether the primitive attribute scaTipoCosto is null.
	 */
	protected boolean scaTipoCostoNull = true;

	/** 
	 * This attribute maps to the column sca_tipo_pag in the struttura_costi_agg table.
	 */
	protected long scaTipoPag;

	/** 
	 * This attribute represents whether the primitive attribute scaTipoPag is null.
	 */
	protected boolean scaTipoPagNull = true;

	/**
	 * Method 'StrutturaCostiAgg'
	 * 
	 */
	public StrutturaCostiAgg()
	{
	}

	/**
	 * Method 'getScaId'
	 * 
	 * @return long
	 */
	public long getScaId()
	{
		return scaId;
	}

	/**
	 * Method 'setScaId'
	 * 
	 * @param scaId
	 */
	public void setScaId(long scaId)
	{
		this.scaId = scaId;
	}

	/**
	 * Method 'getScaDepCauzion'
	 * 
	 * @return String
	 */
	public String getScaDepCauzion()
	{
		return scaDepCauzion;
	}

	/**
	 * Method 'setScaDepCauzion'
	 * 
	 * @param scaDepCauzion
	 */
	public void setScaDepCauzion(String scaDepCauzion)
	{
		this.scaDepCauzion = scaDepCauzion;
	}

	/**
	 * Method 'getScaIncPrezzo'
	 * 
	 * @return String
	 */
	public String getScaIncPrezzo()
	{
		return scaIncPrezzo;
	}

	/**
	 * Method 'setScaIncPrezzo'
	 * 
	 * @param scaIncPrezzo
	 */
	public void setScaIncPrezzo(String scaIncPrezzo)
	{
		this.scaIncPrezzo = scaIncPrezzo;
	}

	/**
	 * Method 'getScaImporto'
	 * 
	 * @return float
	 */
	public float getScaImporto()
	{
		return scaImporto;
	}

	/**
	 * Method 'setScaImporto'
	 * 
	 * @param scaImporto
	 */
	public void setScaImporto(float scaImporto)
	{
		this.scaImporto = scaImporto;
	}

	/**
	 * Method 'getStrutturaStrId'
	 * 
	 * @return long
	 */
	public long getStrutturaStrId()
	{
		return strutturaStrId;
	}

	/**
	 * Method 'setStrutturaStrId'
	 * 
	 * @param strutturaStrId
	 */
	public void setStrutturaStrId(long strutturaStrId)
	{
		this.strutturaStrId = strutturaStrId;
	}

	/**
	 * Method 'getScaTipoCosto'
	 * 
	 * @return long
	 */
	public long getScaTipoCosto()
	{
		return scaTipoCosto;
	}

	/**
	 * Method 'setScaTipoCosto'
	 * 
	 * @param scaTipoCosto
	 */
	public void setScaTipoCosto(long scaTipoCosto)
	{
		this.scaTipoCosto = scaTipoCosto;
		this.scaTipoCostoNull = false;
	}

	/**
	 * Method 'setScaTipoCostoNull'
	 * 
	 * @param value
	 */
	public void setScaTipoCostoNull(boolean value)
	{
		this.scaTipoCostoNull = value;
	}

	/**
	 * Method 'isScaTipoCostoNull'
	 * 
	 * @return boolean
	 */
	public boolean isScaTipoCostoNull()
	{
		return scaTipoCostoNull;
	}

	/**
	 * Method 'getScaTipoPag'
	 * 
	 * @return long
	 */
	public long getScaTipoPag()
	{
		return scaTipoPag;
	}

	/**
	 * Method 'setScaTipoPag'
	 * 
	 * @param scaTipoPag
	 */
	public void setScaTipoPag(long scaTipoPag)
	{
		this.scaTipoPag = scaTipoPag;
		this.scaTipoPagNull = false;
	}

	/**
	 * Method 'setScaTipoPagNull'
	 * 
	 * @param value
	 */
	public void setScaTipoPagNull(boolean value)
	{
		this.scaTipoPagNull = value;
	}

	/**
	 * Method 'isScaTipoPagNull'
	 * 
	 * @return boolean
	 */
	public boolean isScaTipoPagNull()
	{
		return scaTipoPagNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof StrutturaCostiAgg)) {
			return false;
		}
		
		final StrutturaCostiAgg _cast = (StrutturaCostiAgg) _other;
		if (scaId != _cast.scaId) {
			return false;
		}
		
		if (scaDepCauzion == null ? _cast.scaDepCauzion != scaDepCauzion : !scaDepCauzion.equals( _cast.scaDepCauzion )) {
			return false;
		}
		
		if (scaIncPrezzo == null ? _cast.scaIncPrezzo != scaIncPrezzo : !scaIncPrezzo.equals( _cast.scaIncPrezzo )) {
			return false;
		}
		
		if (scaImporto != _cast.scaImporto) {
			return false;
		}
		
		if (strutturaStrId != _cast.strutturaStrId) {
			return false;
		}
		
		if (scaTipoCosto != _cast.scaTipoCosto) {
			return false;
		}
		
		if (scaTipoCostoNull != _cast.scaTipoCostoNull) {
			return false;
		}
		
		if (scaTipoPag != _cast.scaTipoPag) {
			return false;
		}
		
		if (scaTipoPagNull != _cast.scaTipoPagNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (scaId ^ (scaId >>> 32));
		if (scaDepCauzion != null) {
			_hashCode = 29 * _hashCode + scaDepCauzion.hashCode();
		}
		
		if (scaIncPrezzo != null) {
			_hashCode = 29 * _hashCode + scaIncPrezzo.hashCode();
		}
		
		_hashCode = 29 * _hashCode + Float.floatToIntBits(scaImporto);
		_hashCode = 29 * _hashCode + (int) (strutturaStrId ^ (strutturaStrId >>> 32));
		_hashCode = 29 * _hashCode + (int) (scaTipoCosto ^ (scaTipoCosto >>> 32));
		_hashCode = 29 * _hashCode + (scaTipoCostoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) (scaTipoPag ^ (scaTipoPag >>> 32));
		_hashCode = 29 * _hashCode + (scaTipoPagNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return StrutturaCostiAggPk
	 */
	public StrutturaCostiAggPk createPk()
	{
		return new StrutturaCostiAggPk(scaId, strutturaStrId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mysecretwish.dto.StrutturaCostiAgg: " );
		ret.append( "scaId=" + scaId );
		ret.append( ", scaDepCauzion=" + scaDepCauzion );
		ret.append( ", scaIncPrezzo=" + scaIncPrezzo );
		ret.append( ", scaImporto=" + scaImporto );
		ret.append( ", strutturaStrId=" + strutturaStrId );
		ret.append( ", scaTipoCosto=" + scaTipoCosto );
		ret.append( ", scaTipoPag=" + scaTipoPag );
		return ret.toString();
	}

}
