/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dto;

import com.mysecretwish.dao.*;
import com.mysecretwish.factory.*;
import com.mysecretwish.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class StrutturaDatiExtra implements Serializable
{
	/** 
	 * This attribute maps to the column str_data_inizio_attivita in the struttura_dati_extra table.
	 */
	protected Date strDataInizioAttivita;

	/** 
	 * This attribute maps to the column str_data_costruzione in the struttura_dati_extra table.
	 */
	protected Date strDataCostruzione;

	/** 
	 * This attribute maps to the column str_data_ultima_ristr in the struttura_dati_extra table.
	 */
	protected Date strDataUltimaRistr;

	/** 
	 * This attribute maps to the column struttura_str_id in the struttura_dati_extra table.
	 */
	protected long strutturaStrId;

	/** 
	 * This attribute maps to the column dati_estra_id in the struttura_dati_extra table.
	 */
	protected long datiEstraId;

	/** 
	 * This attribute maps to the column str_abit_privata in the struttura_dati_extra table.
	 */
	protected String strAbitPrivata;

	/**
	 * Method 'StrutturaDatiExtra'
	 * 
	 */
	public StrutturaDatiExtra()
	{
	}

	/**
	 * Method 'getStrDataInizioAttivita'
	 * 
	 * @return Date
	 */
	public Date getStrDataInizioAttivita()
	{
		return strDataInizioAttivita;
	}

	/**
	 * Method 'setStrDataInizioAttivita'
	 * 
	 * @param strDataInizioAttivita
	 */
	public void setStrDataInizioAttivita(Date strDataInizioAttivita)
	{
		this.strDataInizioAttivita = strDataInizioAttivita;
	}

	/**
	 * Method 'getStrDataCostruzione'
	 * 
	 * @return Date
	 */
	public Date getStrDataCostruzione()
	{
		return strDataCostruzione;
	}

	/**
	 * Method 'setStrDataCostruzione'
	 * 
	 * @param strDataCostruzione
	 */
	public void setStrDataCostruzione(Date strDataCostruzione)
	{
		this.strDataCostruzione = strDataCostruzione;
	}

	/**
	 * Method 'getStrDataUltimaRistr'
	 * 
	 * @return Date
	 */
	public Date getStrDataUltimaRistr()
	{
		return strDataUltimaRistr;
	}

	/**
	 * Method 'setStrDataUltimaRistr'
	 * 
	 * @param strDataUltimaRistr
	 */
	public void setStrDataUltimaRistr(Date strDataUltimaRistr)
	{
		this.strDataUltimaRistr = strDataUltimaRistr;
	}

	/**
	 * Method 'getStrutturaStrId'
	 * 
	 * @return long
	 */
	public long getStrutturaStrId()
	{
		return strutturaStrId;
	}

	/**
	 * Method 'setStrutturaStrId'
	 * 
	 * @param strutturaStrId
	 */
	public void setStrutturaStrId(long strutturaStrId)
	{
		this.strutturaStrId = strutturaStrId;
	}

	/**
	 * Method 'getDatiEstraId'
	 * 
	 * @return long
	 */
	public long getDatiEstraId()
	{
		return datiEstraId;
	}

	/**
	 * Method 'setDatiEstraId'
	 * 
	 * @param datiEstraId
	 */
	public void setDatiEstraId(long datiEstraId)
	{
		this.datiEstraId = datiEstraId;
	}

	/**
	 * Method 'getStrAbitPrivata'
	 * 
	 * @return String
	 */
	public String getStrAbitPrivata()
	{
		return strAbitPrivata;
	}

	/**
	 * Method 'setStrAbitPrivata'
	 * 
	 * @param strAbitPrivata
	 */
	public void setStrAbitPrivata(String strAbitPrivata)
	{
		this.strAbitPrivata = strAbitPrivata;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof StrutturaDatiExtra)) {
			return false;
		}
		
		final StrutturaDatiExtra _cast = (StrutturaDatiExtra) _other;
		if (strDataInizioAttivita == null ? _cast.strDataInizioAttivita != strDataInizioAttivita : !strDataInizioAttivita.equals( _cast.strDataInizioAttivita )) {
			return false;
		}
		
		if (strDataCostruzione == null ? _cast.strDataCostruzione != strDataCostruzione : !strDataCostruzione.equals( _cast.strDataCostruzione )) {
			return false;
		}
		
		if (strDataUltimaRistr == null ? _cast.strDataUltimaRistr != strDataUltimaRistr : !strDataUltimaRistr.equals( _cast.strDataUltimaRistr )) {
			return false;
		}
		
		if (strutturaStrId != _cast.strutturaStrId) {
			return false;
		}
		
		if (datiEstraId != _cast.datiEstraId) {
			return false;
		}
		
		if (strAbitPrivata == null ? _cast.strAbitPrivata != strAbitPrivata : !strAbitPrivata.equals( _cast.strAbitPrivata )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (strDataInizioAttivita != null) {
			_hashCode = 29 * _hashCode + strDataInizioAttivita.hashCode();
		}
		
		if (strDataCostruzione != null) {
			_hashCode = 29 * _hashCode + strDataCostruzione.hashCode();
		}
		
		if (strDataUltimaRistr != null) {
			_hashCode = 29 * _hashCode + strDataUltimaRistr.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (strutturaStrId ^ (strutturaStrId >>> 32));
		_hashCode = 29 * _hashCode + (int) (datiEstraId ^ (datiEstraId >>> 32));
		if (strAbitPrivata != null) {
			_hashCode = 29 * _hashCode + strAbitPrivata.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return StrutturaDatiExtraPk
	 */
	public StrutturaDatiExtraPk createPk()
	{
		return new StrutturaDatiExtraPk(datiEstraId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mysecretwish.dto.StrutturaDatiExtra: " );
		ret.append( "strDataInizioAttivita=" + strDataInizioAttivita );
		ret.append( ", strDataCostruzione=" + strDataCostruzione );
		ret.append( ", strDataUltimaRistr=" + strDataUltimaRistr );
		ret.append( ", strutturaStrId=" + strutturaStrId );
		ret.append( ", datiEstraId=" + datiEstraId );
		ret.append( ", strAbitPrivata=" + strAbitPrivata );
		return ret.toString();
	}

}
