/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the struttura_trasporti table.
 */
public class StrutturaTrasportiPk implements Serializable
{
	protected long strId;

	/** 
	 * This attribute represents whether the primitive attribute strId is null.
	 */
	protected boolean strIdNull;

	/** 
	 * Sets the value of strId
	 */
	public void setStrId(long strId)
	{
		this.strId = strId;
	}

	/** 
	 * Gets the value of strId
	 */
	public long getStrId()
	{
		return strId;
	}

	/**
	 * Method 'StrutturaTrasportiPk'
	 * 
	 */
	public StrutturaTrasportiPk()
	{
	}

	/**
	 * Method 'StrutturaTrasportiPk'
	 * 
	 * @param strId
	 */
	public StrutturaTrasportiPk(final long strId)
	{
		this.strId = strId;
	}

	/** 
	 * Sets the value of strIdNull
	 */
	public void setStrIdNull(boolean strIdNull)
	{
		this.strIdNull = strIdNull;
	}

	/** 
	 * Gets the value of strIdNull
	 */
	public boolean isStrIdNull()
	{
		return strIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof StrutturaTrasportiPk)) {
			return false;
		}
		
		final StrutturaTrasportiPk _cast = (StrutturaTrasportiPk) _other;
		if (strId != _cast.strId) {
			return false;
		}
		
		if (strIdNull != _cast.strIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (strId ^ (strId >>> 32));
		_hashCode = 29 * _hashCode + (strIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mysecretwish.dto.StrutturaTrasportiPk: " );
		ret.append( "strId=" + strId );
		return ret.toString();
	}

}
