/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dto;

import com.mysecretwish.dao.*;
import com.mysecretwish.factory.*;
import com.mysecretwish.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class StrutturaFoto implements Serializable
{
	/** 
	 * This attribute maps to the column struttura_str_id in the struttura_foto table.
	 */
	protected long strutturaStrId;

	/** 
	 * This attribute maps to the column foto_id in the struttura_foto table.
	 */
	protected long fotoId;

	/** 
	 * This attribute maps to the column foto_descrizione in the struttura_foto table.
	 */
	protected String fotoDescrizione;

	/** 
	 * This attribute maps to the column foto_principale in the struttura_foto table.
	 */
	protected int fotoPrincipale;

	/** 
	 * This attribute maps to the column foto_path in the struttura_foto table.
	 */
	protected String fotoPath;

	/**
	 * Method 'StrutturaFoto'
	 * 
	 */
	public StrutturaFoto()
	{
	}

	/**
	 * Method 'getStrutturaStrId'
	 * 
	 * @return long
	 */
	public long getStrutturaStrId()
	{
		return strutturaStrId;
	}

	/**
	 * Method 'setStrutturaStrId'
	 * 
	 * @param strutturaStrId
	 */
	public void setStrutturaStrId(long strutturaStrId)
	{
		this.strutturaStrId = strutturaStrId;
	}

	/**
	 * Method 'getFotoId'
	 * 
	 * @return long
	 */
	public long getFotoId()
	{
		return fotoId;
	}

	/**
	 * Method 'setFotoId'
	 * 
	 * @param fotoId
	 */
	public void setFotoId(long fotoId)
	{
		this.fotoId = fotoId;
	}

	/**
	 * Method 'getFotoDescrizione'
	 * 
	 * @return String
	 */
	public String getFotoDescrizione()
	{
		return fotoDescrizione;
	}

	/**
	 * Method 'setFotoDescrizione'
	 * 
	 * @param fotoDescrizione
	 */
	public void setFotoDescrizione(String fotoDescrizione)
	{
		this.fotoDescrizione = fotoDescrizione;
	}

	/**
	 * Method 'getFotoPrincipale'
	 * 
	 * @return int
	 */
	public int getFotoPrincipale()
	{
		return fotoPrincipale;
	}

	/**
	 * Method 'setFotoPrincipale'
	 * 
	 * @param fotoPrincipale
	 */
	public void setFotoPrincipale(int fotoPrincipale)
	{
		this.fotoPrincipale = fotoPrincipale;
	}

	/**
	 * Method 'getFotoPath'
	 * 
	 * @return String
	 */
	public String getFotoPath()
	{
		return fotoPath;
	}

	/**
	 * Method 'setFotoPath'
	 * 
	 * @param fotoPath
	 */
	public void setFotoPath(String fotoPath)
	{
		this.fotoPath = fotoPath;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof StrutturaFoto)) {
			return false;
		}
		
		final StrutturaFoto _cast = (StrutturaFoto) _other;
		if (strutturaStrId != _cast.strutturaStrId) {
			return false;
		}
		
		if (fotoId != _cast.fotoId) {
			return false;
		}
		
		if (fotoDescrizione == null ? _cast.fotoDescrizione != fotoDescrizione : !fotoDescrizione.equals( _cast.fotoDescrizione )) {
			return false;
		}
		
		if (fotoPrincipale != _cast.fotoPrincipale) {
			return false;
		}
		
		if (fotoPath == null ? _cast.fotoPath != fotoPath : !fotoPath.equals( _cast.fotoPath )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (strutturaStrId ^ (strutturaStrId >>> 32));
		_hashCode = 29 * _hashCode + (int) (fotoId ^ (fotoId >>> 32));
		if (fotoDescrizione != null) {
			_hashCode = 29 * _hashCode + fotoDescrizione.hashCode();
		}
		
		_hashCode = 29 * _hashCode + fotoPrincipale;
		if (fotoPath != null) {
			_hashCode = 29 * _hashCode + fotoPath.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return StrutturaFotoPk
	 */
	public StrutturaFotoPk createPk()
	{
		return new StrutturaFotoPk(fotoId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mysecretwish.dto.StrutturaFoto: " );
		ret.append( "strutturaStrId=" + strutturaStrId );
		ret.append( ", fotoId=" + fotoId );
		ret.append( ", fotoDescrizione=" + fotoDescrizione );
		ret.append( ", fotoPrincipale=" + fotoPrincipale );
		ret.append( ", fotoPath=" + fotoPath );
		return ret.toString();
	}

}
