/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the struttura_indicazioni table.
 */
public class StrutturaIndicazioniPk implements Serializable
{
	protected long indId;

	/** 
	 * This attribute represents whether the primitive attribute indId is null.
	 */
	protected boolean indIdNull;

	/** 
	 * Sets the value of indId
	 */
	public void setIndId(long indId)
	{
		this.indId = indId;
	}

	/** 
	 * Gets the value of indId
	 */
	public long getIndId()
	{
		return indId;
	}

	/**
	 * Method 'StrutturaIndicazioniPk'
	 * 
	 */
	public StrutturaIndicazioniPk()
	{
	}

	/**
	 * Method 'StrutturaIndicazioniPk'
	 * 
	 * @param indId
	 */
	public StrutturaIndicazioniPk(final long indId)
	{
		this.indId = indId;
	}

	/** 
	 * Sets the value of indIdNull
	 */
	public void setIndIdNull(boolean indIdNull)
	{
		this.indIdNull = indIdNull;
	}

	/** 
	 * Gets the value of indIdNull
	 */
	public boolean isIndIdNull()
	{
		return indIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof StrutturaIndicazioniPk)) {
			return false;
		}
		
		final StrutturaIndicazioniPk _cast = (StrutturaIndicazioniPk) _other;
		if (indId != _cast.indId) {
			return false;
		}
		
		if (indIdNull != _cast.indIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (indId ^ (indId >>> 32));
		_hashCode = 29 * _hashCode + (indIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mysecretwish.dto.StrutturaIndicazioniPk: " );
		ret.append( "indId=" + indId );
		return ret.toString();
	}

}
