/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the struttura_cond_pagamento table.
 */
public class StrutturaCondPagamentoPk implements Serializable
{
	protected long scpId;

	/** 
	 * This attribute represents whether the primitive attribute scpId is null.
	 */
	protected boolean scpIdNull;

	/** 
	 * Sets the value of scpId
	 */
	public void setScpId(long scpId)
	{
		this.scpId = scpId;
	}

	/** 
	 * Gets the value of scpId
	 */
	public long getScpId()
	{
		return scpId;
	}

	/**
	 * Method 'StrutturaCondPagamentoPk'
	 * 
	 */
	public StrutturaCondPagamentoPk()
	{
	}

	/**
	 * Method 'StrutturaCondPagamentoPk'
	 * 
	 * @param scpId
	 */
	public StrutturaCondPagamentoPk(final long scpId)
	{
		this.scpId = scpId;
	}

	/** 
	 * Sets the value of scpIdNull
	 */
	public void setScpIdNull(boolean scpIdNull)
	{
		this.scpIdNull = scpIdNull;
	}

	/** 
	 * Gets the value of scpIdNull
	 */
	public boolean isScpIdNull()
	{
		return scpIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof StrutturaCondPagamentoPk)) {
			return false;
		}
		
		final StrutturaCondPagamentoPk _cast = (StrutturaCondPagamentoPk) _other;
		if (scpId != _cast.scpId) {
			return false;
		}
		
		if (scpIdNull != _cast.scpIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (scpId ^ (scpId >>> 32));
		_hashCode = 29 * _hashCode + (scpIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mysecretwish.dto.StrutturaCondPagamentoPk: " );
		ret.append( "scpId=" + scpId );
		return ret.toString();
	}

}
