/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the struttura_messaggi table.
 */
public class StrutturaMessaggiPk implements Serializable
{
	protected long mesId;

	/** 
	 * This attribute represents whether the primitive attribute mesId is null.
	 */
	protected boolean mesIdNull;

	/** 
	 * Sets the value of mesId
	 */
	public void setMesId(long mesId)
	{
		this.mesId = mesId;
	}

	/** 
	 * Gets the value of mesId
	 */
	public long getMesId()
	{
		return mesId;
	}

	/**
	 * Method 'StrutturaMessaggiPk'
	 * 
	 */
	public StrutturaMessaggiPk()
	{
	}

	/**
	 * Method 'StrutturaMessaggiPk'
	 * 
	 * @param mesId
	 */
	public StrutturaMessaggiPk(final long mesId)
	{
		this.mesId = mesId;
	}

	/** 
	 * Sets the value of mesIdNull
	 */
	public void setMesIdNull(boolean mesIdNull)
	{
		this.mesIdNull = mesIdNull;
	}

	/** 
	 * Gets the value of mesIdNull
	 */
	public boolean isMesIdNull()
	{
		return mesIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof StrutturaMessaggiPk)) {
			return false;
		}
		
		final StrutturaMessaggiPk _cast = (StrutturaMessaggiPk) _other;
		if (mesId != _cast.mesId) {
			return false;
		}
		
		if (mesIdNull != _cast.mesIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (mesId ^ (mesId >>> 32));
		_hashCode = 29 * _hashCode + (mesIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mysecretwish.dto.StrutturaMessaggiPk: " );
		ret.append( "mesId=" + mesId );
		return ret.toString();
	}

}
