/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dto;

import com.mysecretwish.dao.*;
import com.mysecretwish.factory.*;
import com.mysecretwish.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class TipologiaPromozione implements Serializable
{
	/** 
	 * This attribute maps to the column tpp_id in the tipologia_promozione table.
	 */
	protected long tppId;

	/** 
	 * This attribute maps to the column tpp_descrizione in the tipologia_promozione table.
	 */
	protected String tppDescrizione;

	/**
	 * Method 'TipologiaPromozione'
	 * 
	 */
	public TipologiaPromozione()
	{
	}

	/**
	 * Method 'getTppId'
	 * 
	 * @return long
	 */
	public long getTppId()
	{
		return tppId;
	}

	/**
	 * Method 'setTppId'
	 * 
	 * @param tppId
	 */
	public void setTppId(long tppId)
	{
		this.tppId = tppId;
	}

	/**
	 * Method 'getTppDescrizione'
	 * 
	 * @return String
	 */
	public String getTppDescrizione()
	{
		return tppDescrizione;
	}

	/**
	 * Method 'setTppDescrizione'
	 * 
	 * @param tppDescrizione
	 */
	public void setTppDescrizione(String tppDescrizione)
	{
		this.tppDescrizione = tppDescrizione;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TipologiaPromozione)) {
			return false;
		}
		
		final TipologiaPromozione _cast = (TipologiaPromozione) _other;
		if (tppId != _cast.tppId) {
			return false;
		}
		
		if (tppDescrizione == null ? _cast.tppDescrizione != tppDescrizione : !tppDescrizione.equals( _cast.tppDescrizione )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (tppId ^ (tppId >>> 32));
		if (tppDescrizione != null) {
			_hashCode = 29 * _hashCode + tppDescrizione.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TipologiaPromozionePk
	 */
	public TipologiaPromozionePk createPk()
	{
		return new TipologiaPromozionePk(tppId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mysecretwish.dto.TipologiaPromozione: " );
		ret.append( "tppId=" + tppId );
		ret.append( ", tppDescrizione=" + tppDescrizione );
		return ret.toString();
	}

}
