/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mysecretwish.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the visibilita table.
 */
public class VisibilitaPk implements Serializable
{
	protected long visId;

	/** 
	 * This attribute represents whether the primitive attribute visId is null.
	 */
	protected boolean visIdNull;

	/** 
	 * Sets the value of visId
	 */
	public void setVisId(long visId)
	{
		this.visId = visId;
	}

	/** 
	 * Gets the value of visId
	 */
	public long getVisId()
	{
		return visId;
	}

	/**
	 * Method 'VisibilitaPk'
	 * 
	 */
	public VisibilitaPk()
	{
	}

	/**
	 * Method 'VisibilitaPk'
	 * 
	 * @param visId
	 */
	public VisibilitaPk(final long visId)
	{
		this.visId = visId;
	}

	/** 
	 * Sets the value of visIdNull
	 */
	public void setVisIdNull(boolean visIdNull)
	{
		this.visIdNull = visIdNull;
	}

	/** 
	 * Gets the value of visIdNull
	 */
	public boolean isVisIdNull()
	{
		return visIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof VisibilitaPk)) {
			return false;
		}
		
		final VisibilitaPk _cast = (VisibilitaPk) _other;
		if (visId != _cast.visId) {
			return false;
		}
		
		if (visIdNull != _cast.visIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (visId ^ (visId >>> 32));
		_hashCode = 29 * _hashCode + (visIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mysecretwish.dto.VisibilitaPk: " );
		ret.append( "visId=" + visId );
		return ret.toString();
	}

}
