CREATE SEQUENCE seq_tabelle_dominio INCREMENT 1  START 1;

CREATE SEQUENCE seq_prenotazioni INCREMENT 1  START 1;

CREATE SEQUENCE seq_preventivi INCREMENT 1  START 1;

CREATE SEQUENCE seq_strutture INCREMENT 1  START 1;

CREATE SEQUENCE seq_messaggi INCREMENT 1  START 1;

CREATE SEQUENCE seq_utenti INCREMENT 1  START 1;

CREATE SEQUENCE seq_camere INCREMENT 1  START 1;

CREATE SEQUENCE seq_foto INCREMENT 1  START 1;








